version: "3"

services:
  servers:
    build: ./server
    container_name: servers
    networks:
      - xzh
    ports:
      - 5050:5050
    depends_on:
      - mongodb
      
  mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/x_zh/mongodb
    container_name: database
    logging:
      driver: json-file
      options:
        max-size: "64m"
        max-file: "10"
    volumes:
      - /data/db:/data/db
    networks:
      - xzh
    ports:
      - 49155:27017

networks:
  xzh:
    driver: bridge