version: "3"

services:
  servers:
    image: registry.cn-hangzhou.aliyuncs.com/x_zh/servers
    container_name: servers
    ports:
      - 80:80
    networks: 
      - xzh

  mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/x_zh/mongodb
    container_name: database
    logging:
      driver: json-file
      options:
        max-size: "64m"
        max-file: "10"
    volumes:
      - /data/db:/data/db
    networks:
      - xzh
    ports:
      - 27017:27017

networks:
  xzh:
    driver: bridge